name: CI

on:
  push:
    branches: [Staging]
  pull_request:
    branches: [Staging]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip --version
          make setup
  
      - uses: actions/checkout@v3
      - name: Remove the venv and __pycache__
        run: make clean
  
  features_tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Test with pytest
        run: |
          echo ok
