name: Build

on:
  push:
    branches: [Staging]
  pull_request:
    branches: [Staging]

jobs:
  set_token_var:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v3
      with:
        ref: 'Staging'
    - name: Add TOKEN variable inside a .config file
      run: echo "TOKEN=${{ secrets.TOKEN }}" > .config && cat .config

  build:
    runs-on: ubuntu-latest
    needs: set_token_var
    steps:
    - name: Install python3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: build dependencies and run the program
      run: make run
      timeout-minutes: 2

  check_repository_cleanliness:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Remove the venv and __pycache__
      run: make clean
