name: Build

on:
  push:
    branches: [Staging]
  pull_request:
    branches: [Staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v3
      with:
        ref: 'Staging'

    - name: Install python3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Display python version
      run: python -c "import sys; print(sys.version)"

    - uses: actions/checkout@v3
    - name: build dependencies and test discord module
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        make setup

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - uses: actions/checkout@v3
    - name: Remove the venv and __pycache__
      run: make clean
      
  features_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Test with pytest
      run: |
          pytest
