name: Build

on:
  push:
    branches: [Staging]
  pull_request:
    branches: [Staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v3
      with:
        ref: 'Staging'

    - name: Install python3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Display python version
      run: python -c "import sys; print(sys.version)"

    - uses: actions/checkout@v3
    - name: build dependencies and test discord module
      run: |
        python -m pip install --upgrade pip
        make setup

    - uses: actions/checkout@v3
    - name: Remove the venv and __pycache__
      run: make clean
      
  features_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Test with pytest
      run: |
          pytest
